### ISSUE TITLE
Feature Request: Human structures location

### ISSUE THREAD

**Issue by Twomoon-Github** [pontsci/gateway-isle-map-issues#1]
Description:
Introduce human structures locations on the map, maybe toggle it off by default for those that want to find them on their own without using the map, also maybe adding bridges etc
I found these structures, i dont know the official names except K15, and i maybe missed some, but if that can help...

(btw great works, thanks a lot)
![gateway](https://github.com/pontsci/gateway-isle-map-issues/assets/45800756/04a71d13-c0ec-4a07-8045-09d09fac456b)

**Comment by pontsci** [comment]
We're working on this now actually, glad you like the map so far!
