### ISSUE TITLE
Feature Request: Sanctuaries

### ISSUE THREAD

**Issue by Twomoon-Github** [pontsci/gateway-isle-map-issues#3]
its new, and i dont know where they all are, but i imagine it would be nice on the map, great work on the map and the human structures, i would suggest modifying the swamp tunnel on the map, its barely visible as human structure, perhaps adding the tunnel name would help. :>

**Comment by ratbits** [comment]
Swamp one is at 281,548.523, 27,451.598,  20,328.37

**Comment by Emeara** [comment]
Alright, these should all be added now! We got the three sanctuaries added in and I think adding the text for the swamp tunnel is be really helpful for players!
